# CodeRabbit Configuration
language: ja
reviews:
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    ruff:
      enabled: true
    shellcheck:
      enabled: true
    yamllint:
      enabled: true
chat:
  auto_reply: true
